# Generated by Django 4.1.7 on 2023-02-25 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=100)),
                ('icon_color', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_name', models.CharField(max_length=100)),
                ('url_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProgressItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('progress_start', models.CharField(max_length=100)),
                ('duration', models.IntegerField()),
                ('type', models.CharField(choices=[('diamond', 'diamond'), ('favorite', 'favorite'), ('spa', 'spa'), ('eco', 'eco')], default='diamond', max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='card',
            name='rank',
            field=models.CharField(choices=[('diamond', 'diamond'), ('heart', 'heart'), ('club', 'club'), ('spade', 'spade')], default='diamond', max_length=10),
        ),
    ]
